export const Colors = {
    light: {
        darkBlue: "#140A59",
        mediumBlue: "#002055",
        lightBlue: "#63B4FF",
        mediumPurple: "#8B90C1",
        lightPurple: "#C6C3FB",
        darkOrange: "#FF9A00",
        lightOrange: "#FED883", 
        lightGreen: "#B1D199",
        mediumbrown: "#B18A4A",
        mediumYellow: "#DAC342",
        lightYellow: "#F4DD7D",
        mediumGray: "#848A94",
        lightGray: "#868D95",
        white: "#FFFFFF",
    }, 
    dark: {
        extraDarkBlue: "#140A59",
        veryDarkBlue: "#1E1675",
        darkBlue: "#11065A",
        mediumBlue: "#342C7D",
        blue: "#3C2FC0",
        blueSky: "#63B4FF",
        lightGray: "#C7CED5",
        darkWhite: "#C7CAE8",
        white: "#FFFFFF",
        darkOrange: "#FF9A00",
        mediumOrange: "#F4DD7D",
        lightOrange: "#FED883",
        darkPurple: "#3C2FC0",
        purple: "#928CFF",
        mediumPurple: "#8B90C1",
        lightPurple: "#C6C3FB",
        veryLightPurple: "#B4B1EB",
        extraLightPurple: "#C6C3FB",
    },
    home: {
        orange: "#FF9A00",
        lightOrange: "#C9A84C",
        darkBlue: "#11065A",
        mediumBlue: "#140A59",
        darkPurple: "#5F65A1",
        mediumPurple: "#777DB7",
        lightPurple: "#8F88BB",
        white: "#F8F6FF",
        lightWhite: "#C7CAE8CC",
    },
    stats: {
        lightGreen: "#B1D199",
        darkPurple: "#756EF3",
        blueSky: "#5A96FF",
        mediumOrange: "#FFB35A",
    }

}